# 配置数据源相关 使用阿里巴巴的Druid 数据源
spring:
  datasource:
    url: jdbc:mysql://188.131.133.149:3306/br-video
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml

#通用 Mapper 配置
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  notEmpty: true

# Server 服务器相关配置
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

